### PR TITLE
Add get all elements

### LINKED ISSUE #70: Deviser does not generate getAllElements
It would seem that the getAllElements functions are not being generated. It would also be nice to have the ElementFilter functionality as we have it in libSBML automatically generated.

### PR DESCRIPTION
**Pull request by skeating**
## Description
Other libraries aso need to write getAllElements

fixes #70 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated all documentation necessary.
- [ ] I have checked spelling in (new) comments.

### CODE REVIEW

**Comment by fbergmann** [comment]
@skeating Thank you soo much, this does make my work much easier! i still think we should use a dedicated ElementFilter class for other libraries, otherwise at the latest it would stop breaking down when a library has a member with elements from two libraries. That would have to be navigated, then there really needs to be a `<LanguagePrefix>ElementFilter` class, and the corresponding `<LANGUAGE_PREFIX>_ADD...` macros.

**Comment by fbergmann** [comment]
while merging the generated code, `math` nodes (ASTNode) should not be added to the list, as the list should be base class derived.

**Comment by skeating** [comment]
added the bits to make lib specific element filter and macros

Not sure what your aother comment meant

**Comment by fbergmann** [comment]
> Not sure what your aother comment meant

Basically there was a `ADD_FILTERED_POINTER` line generated for the `mMath` elements of type `ASTNode*`. I was proposing that for math members no such line is generated, as the underlying type is not derived from the baseclass.

**Comment by skeating** [comment]
Done. Can merge but please dont delete branch

**Review by fbergmann — COMMENTED** [review]
it is really unfortunate that the SED-ML model had line ending format changes, which makes it hard to see what was changed. But i believe tht is fine.

**Review by fbergmann — APPROVED** [review]
but it does look fine to me

**Pull request merged**
