### PR TITLE
Add testsbxml

### PR DESCRIPTION
**Pull request by skeating**
## Description

Adding testsbxml as a test-other library test
and changing test files affected 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have updated all documentation necessary.
- [ ] I have checked spelling in (new) comments.

### CODE REVIEW

**Review by fbergmann — CHANGES_REQUESTED** [review]
@skeating i can understand why these changes are necessary. I would just want to ask you to first tag the release branch before the merge, as the generated code is not compatible with what was generated before. So we need an update to `VERSION.txt` and a tag. then I'd be happy to approve. 

Ideally the cmake code would be updated to current CMake (i.e. using import targets that contain the include directory and flags needed to build) that would simplify the code changes a bit. But that can come in later. 

i hope that is ok

**Comment by skeating** [comment]
tagged existing dev branch and changed version here to 2.0

**Comment by skeating** [comment]
@fbergmann happy for me to merge now ?

other PRs I'll get reviewed here

**Review by fbergmann — APPROVED** [review]
thank you so much for the new tag.

**Pull request merged**
