### PR TITLE
Fixed a bug that stopped Tex tests working.

### PR DESCRIPTION
**Pull request by mattagape**
The tex tests now work under Python 3. They didn't before.

Unfortunately, this fix does not work under Python 2, as `super()` then requires arguments.

### CODE REVIEW

**Review by skeating — COMMENTED** [review]
This doesnt work for me i.e. it crashes.

**Comment by mattagape** [comment]
@skeating with python3?

**Comment by skeating** [comment]
Yep Python 3.7

throws an exception
'bad escape \\S'

will look next week

**Review by skeating — APPROVED** [review]
Now all tests pass on 2.7/3.5 & 3.7
@mattgillucl  can you check it runs for you before merging

**Comment by mattagape** [comment]
All tests run on Python 3.6.5.
Thanks Sarah.

**Pull request merged**
